@startuml
class UserService {
  - {static} userRepository : UserRepository
  - passwordEncoder : BCryptPasswordEncoder
  + {static} USER_KEY : String
  + {static} USERNAME_KEY : String
  
  + UserService(UserRepository userRepository)
  + {static} isUserAuthenticated() : boolean
  + {static} getAuthenticatedUser() : User
  + {static} clearAuthenticatedUser() : void
  + registerUser(String fullName, String email, String password) : User
  + authenticateUser(String email, String password) : User
  + getCurrentUser() : User
  + logout() : void
  + updateProfilePicture(User user) : void
  + updateProfilePicture(String userId, String profilePicData) : void
  + updateProfilePictureByEmail(String email, String profilePicData) : void
  + {static} getUserById(String email) : User
  + {static} getUserByEmail(String email) : User
  + deleteUserByEmail(String email) : void
  + {static} getAllUsers() : List<User>
}


@enduml