vaadin.launch-browser=true
spring.application.name=smalltalk

spring.data.mongodb.uri=mongodb://localhost:27017/smalltalk
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=smalltalk

# For unlimited upload file size
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

logging.level.root=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

logging.level.ip.test=INFO

logging.level.org.springframework=WARN
logging.level.org.apache=WARN
logging.level.com.vaadin=WARN
logging.exception-conversion-word=%wEx


