vaadin.launch-browser=true
spring.application.name=smalltalk

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://ulilelmichael:12345@cluster0.hfb0biz.mongodb.net/smalltalk

# Server port (optional)
server.port=8080

# Logging configuration for MongoDB operations - useful for debugging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# For unlimited upload file size
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

logging.level.root=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

logging.level.ip.test=INFO

logging.level.org.springframework=WARN
logging.level.org.apache=WARN
logging.level.com.vaadin=WARN
logging.exception-conversion-word=%wEx


